openapi: 3.0.0
info:
  version: '0.2'
  title: "Explento OpenAPI 3.0"
  description: "REST API documentation for the Explento web platform"

servers:
  - url: http://localhost:3000/api/v1
    description: Local development server

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
        email:
          type: string
        name:
          type: string
        surname:
          type: string
        profileImage:
          type: string
        preferences:
          type: array
          items:
            type: string
        expert:
          type: boolean
        exp:
          type: integer
        places:
          type: array
          items:
            type: object
            properties:
              placeId:
                type: string
              visit:
                type: object
                properties:
                  visited:
                    type: boolean
                  date:
                    type: string
                    format: date-time
        missionsProgress:
          type: array
          items:
            type: object
            properties:
              missionId:
                type: string
              visitedPlaces:
                type: array
                items:
                  type: object
                  properties:
                    placeId:
                      type: string
              progress:
                type: number
              completed:
                type: boolean

    Place:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        description:
          type: string
        categories:
          type: array
          items:
            type: string
        location:
          type: object
          properties:
            lat:
              type: number
              format: float
            lon:
              type: number
              format: float
        images:
          type: array
          items:
            type: string
        isFree:
          type: boolean

    Mission:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        description:
          type: string
        minLevel:
          type: integer
        rewardExp:
          type: integer
        categories:
          type: array
          items:
            type: string
        places:
          type: array
          items:
            type: object
            properties:
              placeId:
                type: string
        requiredCount:
          type: integer

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    RegistrationRequest:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        username:
          type: string
        password:
          type: string
      required:
        - name
        - surname
        - username
        - password
        - email

    UserLocation:
      type: object
      required:
        - lat
        - lng
      properties:
        lat:
          type: number
          format: float
        lng:
          type: number
          format: float

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: boolean
        message:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      summary: "User authentication"
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: "Authentication successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          description: "Invalid credentials"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/register:
    post:
      summary: "User registration"
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationRequest"
      responses:
        200:
          description: "User registered successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: "Invalid data or user already exists"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/operator/login:
    post:
      summary: "Operator authentication"
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: "Operator authenticated"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          description: "Invalid operator credentials"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /me:
    get:
      summary: "Get authenticated user profile"
      description: "Return full user data for the authenticated user."
      tags:
        - Users
      security:
        - BearerAuth: []
      responses:
        200:
          description: "User profile returned successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /me/visit/{placeId}:
    post:
      summary: "Mark a place as visited"
      description: "Mark a place as visited for the authenticated user, optionally including location."
      tags:
        - Users
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: placeId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLocation"
      responses:
        200:
          description: "Place successfully marked as visited."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: "Could not mark place as visited."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /places:
    get:
      summary: "List all places"
      security:
        - BearerAuth: []
      description: "Return all places in the system."
      tags:
        - Places
      responses:
        200:
          description: "List of places returned."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Place"

  /places/{id}:
    get:
      summary: "Place details"
      security:
        - BearerAuth: []
      description: "Return detailed info about a place by its ID."
      tags:
        - Places
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Place returned successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Place"
        404:
          description: "Place not found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /missions:
    get:
      summary: "List all missions"
      security:
        - BearerAuth: []
      description: "Return all missions in the system."
      tags:
        - Missions
      responses:
        200:
          description: "List of missions returned."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Mission"

  /missions/{id}:
    get:
      summary: "Mission details"
      description: "Return detailed info about a mission by its ID."
      security:
        - BearerAuth: []
      tags:
        - Missions
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Mission returned successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mission"
        404:
          description: "Mission not found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
