openapi: 3.0.3
info:
  title: API Specification for Explento WebApp
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1

paths:

  ##########################
  # AUTH
  ##########################

  /auth/login:
    post:
      summary: Login utente
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required: [username, password]
      responses:
        "200":
          description: Login effettuato
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Credenziali non valide

  /auth/register:
    post:
      summary: Registrazione utente
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                name:
                  type: string
                surname:
                  type: string
                password:
                  type: string
              required: [username, email, name, surname, password]
      responses:
        "201":
          description: Utente registrato
        "400":
          description: Dati non validi

  ##########################
  # ME
  ##########################

  /me:
    get:
      summary: Ottieni informazioni sull'utente autenticato
      tags: [Me]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Informazioni utente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Non autorizzato

  /me/visit/{id}:
    post:
      summary: Registra la visita di un luogo tramite coordinate GPS
      tags: [Me]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lat:
                  type: number
                lon:
                  type: number
              required: [lat, lon]
      responses:
        "200":
          description: Visita registrata
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
        "400":
          description: Errore di validazione
        "401":
          description: Non autorizzato

  ##########################
  # USERS
  ##########################

  /users:
    get:
      summary: Ottieni lista utenti
      tags: [Users]
      parameters:
        - name: expert
          in: query
          schema:
            type: boolean
      responses:
        "200":
          description: Lista utenti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

  /users/{username}:
    get:
      summary: Ottieni utente tramite username
      tags: [Users]
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Utente trovato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Utente non trovato

  ##########################
  # OPERATOR
  ##########################

  /operator/login:
    post:
      summary: Login operatore
      tags: [Operator]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required: [email, password]
      responses:
        "200":
          description: Login effettuato
        "401":
          description: Credenziali non valide

  /operator/place_edit_requests:
    get:
      summary: Ottieni tutte le richieste di modifica luogo
      tags: [Operator]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista richieste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlaceEdit"

  /operator/place_edit_requests/{id}:
    get:
      summary: Ottieni una specifica richiesta di modifica
      tags: [Operator]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Richiesta trovata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaceEdit"
        "404":
          description: Richiesta non trovata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    post:
      summary: Aggiorna lo stato di una richiesta di modifica
      tags: [Operator]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [pending, approved, rejected]
                operatorComment:
                  type: string
      responses:
        "200":
          description: Stato aggiornato
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
        "400":
          description: Errore richiesta non valida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Richiesta non trovata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    ##########################
    # USER
    ##########################

    User:
      type: object
      properties:
        id: { type: string }
        username: { type: string }
        email: { type: string }
        name: { type: string }
        surname: { type: string }
        profileImage: { type: string }
        preferences:
          type: array
          items: { type: string }
        expert: { type: boolean }
        exp: { type: number }
        visitedPlaces:
          type: array
          items:
            $ref: "#/components/schemas/VisitedPlace"
        suggestedPlaces:
          type: array
          items:
            $ref: "#/components/schemas/VisitedPlace"
        missionsProgresses:
          type: array
          items:
            $ref: "#/components/schemas/MissionProgress"

    VisitedPlace:
      type: object
      properties:
        placeId: { type: string }
        visited: { type: boolean }
        date:
          type: string
          format: date-time

    MissionProgress:
      type: object
      properties:
        missionId: { type: string }
        requiredPlacesVisited:
          type: array
          items:
            type: object
            properties:
              placeId: { type: string }
        progress: { type: number }
        completed: { type: boolean }

    ##########################
    # OPERATOR
    ##########################

    Operator:
      type: object
      properties:
        id: { type: string }
        email: { type: string }
        role: { type: string }
        name: { type: string }
        surname: { type: string }

    ##########################
    # PLACE
    ##########################

    Place:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        description: { type: string }
        categories:
          type: array
          items: { type: string }
        location:
          type: object
          properties:
            lat: { type: number }
            lon: { type: number }
        images:
          type: array
          items: { type: string }
        isFree: { type: boolean }

    ##########################
    # MISSIONS
    ##########################

    Mission:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        description: { type: string }
        minLevel: { type: number }
        rewardExp: { type: number }
        categories:
          type: array
          items: { type: string }
        requiredPlaces:
          type: array
          items:
            type: object
            properties:
              placeId: { type: string }
        requiredCount: { type: number }

    ##########################
    # PLACE EDIT REQUEST
    ##########################

    PlaceEdit:
      type: object
      properties:
        id: { type: string }
        placeId: { type: string }
        userId: { type: string }
        proposedChanges:
          type: object
        status:
          type: string
          enum: [pending, approved, rejected]
        operatorId: { type: string }
        operatorComment: { type: string }
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: string

