openapi: 3.0.3
info:
  title: API Specification for Explento WebApp
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1

paths:

  ##########################
  # AUTH
  ##########################

  /auth/login:
    post:
      summary: Login utente
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required: [username, password]
      responses:
        "200":
          description: Login effettuato, restituisce JWT
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "400":
          description: Credenziali non valide
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /auth/register:
    post:
      summary: Registrazione utente
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                name:
                  type: string
                surname:
                  type: string
                password:
                  type: string
              required: [username, email, name, surname, password]
      responses:
        "201":
          description: Utente registrato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Dati non validi
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  ##########################
  # ME
  ##########################

  /me:
    get:
      summary: Ottieni informazioni sull'utente autenticato
      tags: [Me]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Informazioni utente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Non autorizzato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /me/visit/{id}:
    post:
      summary: Registra la visita di un luogo tramite coordinate GPS
      tags: [Me]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lat:
                  type: number
                lon:
                  type: number
              required: [lat, lon]
      responses:
        "200":
          description: Visita registrata
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        "400":
          description: Errore di validazione
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Non autorizzato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /me/preferences:
    post:
      summary: Aggiorna le preferenze dell'utente
      tags: [Me]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                alsoPaid:
                  type: boolean
                categories:
                  type: array
                  items:
                    type: string
              required: [alsoPaid, categories]
      responses:
        "200":
          description: Preferenze aggiornate
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Dati mancanti o non validi
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  ##########################
  # USERS
  ##########################

  /users:
    get:
      summary: Ottieni lista utenti
      tags: [Users]
      parameters:
        - name: expert
          in: query
          schema:
            type: boolean
      responses:
        "200":
          description: Lista utenti in formato pubblico
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    self:
                      type: string
                    username:
                      type: string
                    exp:
                      type: number
                    profileImage:
                      type: string
        "500":
          description: Errore server

  /users/{username}:
    get:
      summary: Ottieni utente tramite username
      tags: [Users]
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Utente trovato in formato pubblico
          content:
            application/json:
              schema:
                type: object
                properties:
                  self:
                    type: string
                  username:
                    type: string
                  exp:
                    type: number
                  profileImage:
                    type: string
        "404":
          description: Utente non trovato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  ##########################
  # OPERATOR
  ##########################

  /operator/login:
    post:
      summary: Login operatore
      tags: [Operator]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required: [email, password]
      responses:
        "200":
          description: Login effettuato, restituisce JWT
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "400":
          description: Credenziali non valide
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /operator/me:
    get:
      summary: Ottieni informazioni operatore autenticato
      tags: [Operator]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Operatore trovato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Operator"
        "401":
          description: Non autorizzato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /operator/place_edit_requests:
    get:
      summary: Ottieni richieste di modifica luoghi
      tags: [Operator]
      security:
        - bearerAuth: []
      parameters:
        - name: placeId
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, approved, rejected]
        - name: isNewPlace
          in: query
          schema:
            type: boolean
      responses:
        "200":
          description: Lista richieste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PlaceEdit"
        "400":
          description: Parametri non validi
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /operator/place_edit_requests/{id}:
    get:
      summary: Ottieni richiesta di modifica specifica
      tags: [Operator]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Richiesta trovata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaceEdit"
        "404":
          description: Richiesta non trovata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    patch:
      summary: Aggiorna stato richiesta
      tags: [Operator]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [pending, approved, rejected]
                operatorComment:
                  type: string
      responses:
        "200":
          description: Stato aggiornato
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        "400":
          description: Errore richiesta non valida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Richiesta non trovata
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  ##########################
  # PLACES
  ##########################

  /places:
    get:
      summary: Lista tutti i luoghi
      tags: [Places]
      security:
        - bearerAuth: []
      parameters:
        - name: lat
          in: query
          schema: { type: number }
        - name: lon
          in: query
          schema: { type: number }
        - name: radius
          in: query
          schema: { type: number }
      responses:
        "200":
          description: Lista luoghi filtrata
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Place"
        "500":
          description: Errore server

  /places/request:
    post:
      summary: Richiesta nuovo luogo
      tags: [Places]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                description: { type: string }
                categories:
                  type: array
                  items: { type: string }
                location:
                  type: object
                  properties:
                    lat: { type: number }
                    lon: { type: number }
                images:
                  type: array
                  items: { type: string }
                isFree: { type: boolean }
              required: [name, description, categories, location, isFree]
      responses:
        "201":
          description: Richiesta creata
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  request:
                    $ref: "#/components/schemas/PlaceEdit"
        "400":
          description: Dati non validi
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Utente non autenticato o non esperto
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /places/{id}:
    put:
      summary: Richiesta modifica luogo esistente
      tags: [Places]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                description: { type: string }
                categories:
                  type: array
                  items: { type: string }
                location:
                  type: object
                  properties:
                    lat: { type: number }
                    lon: { type: number }
                images:
                  type: array
                  items: { type: string }
                isFree: { type: boolean }
      responses:
        "201":
          description: Richiesta modifica inviata
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  request:
                    $ref: "#/components/schemas/PlaceEdit"
        "400":
          description: Dati non validi
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Utente non autenticato
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  ##########################
  # HEATMAP
  ##########################

  /heatmap/missions:
    get:
      summary: Heatmap delle missioni completate per luogo
      tags: [Heatmap]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista luoghi con conteggio missioni completate
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    placeId:
                      type: string
                    completedMissions:
                      type: number
                    name:
                      type: string
                    location:
                      type: object
                      properties:
                        lat: { type: number }
                        lon: { type: number }
        "500":
          description: Errore server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    User:
      type: object
      properties:
        id: { type: string }
        username: { type: string }
        email: { type: string }
        name: { type: string }
        surname: { type: string }
        profileImage: { type: string }
        preferences:
          type: object
          properties:
            alsoPaid: { type: boolean }
            categories:
              type: array
              items: { type: string }
        expert: { type: boolean }
        exp: { type: number }
        visitedPlaces:
          type: array
          items:
            $ref: "#/components/schemas/VisitedPlace"
        suggestedPlaces:
          type: array
          items:
            $ref: "#/components/schemas/VisitedPlace"
        missionsProgresses:
          type: array
          items:
            $ref: "#/components/schemas/MissionProgress"

    VisitedPlace:
      type: object
      properties:
        placeId: { type: string }
        visited: { type: boolean }
        date:
          type: string
          format: date-time

    MissionProgress:
      type: object
      properties:
        missionId: { type: string }
        requiredPlacesVisited:
          type: array
          items:
            type: object
            properties:
              placeId: { type: string }
        progress: { type: number }
        completed: { type: boolean }

    Operator:
      type: object
      properties:
        id: { type: string }
        email: { type: string }
        role: { type: string }
        name: { type: string }
        surname: { type: string }

    Place:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        description: { type: string }
        categories:
          type: array
          items: { type: string }
        location:
          type: object
          properties:
            lat: { type: number }
            lon: { type: number }
        images:
          type: array
          items: { type: string }
        isFree: { type: boolean }

    PlaceEdit:
      type: object
      properties:
        id: { type: string }
        placeId: { type: string }
        userId: { type: string }
        proposedChanges:
          type: object
        status:
          type: string
          enum: [pending, approved, rejected]
        operatorId: { type: string }
        operatorComment: { type: string }
        isNewPlace: { type: boolean }
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
